name: box_transform
description: A pure dart implementation of advanced 2D box transformation with easy and simple API.

version: 0.4.4

repository: https://github.com/hyper-designed/box_transform/tree/main/packages/box_transform
homepage: https://github.com/hyper-designed/box_transform/tree/main/packages/box_transform
issue_tracker: https://github.com/hyper-designed/box_transform/issues
documentation: https://docs.page/hyper-designed/box_transform

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
  coverage: ^1.8.0

topics:
  - rectangle
  - box
  - transform
  - utility
  - tool
